### ISSUE TITLE
The return value of Effect.IsActiveType() is wrong sometimes.

### ISSUE THREAD

**Issue by mallu11** [Fluorohydride/ygopro-core#291] opened 2020-02-18 14:52 UTC
Here is example:
Your opponent controls a `Topologic Bomber Dragon` and you control a `Millennium-Eyes Restrict`.
And c1 and c2 are both special summon a monster in the linked zone(or special summon monsters twice in one chain and those monsters are both in the linked zone).
After the chain resolves,`Topologic Bomber Dragon` will activate its effect twice(Here is a bug.According to KONAMI's answer,`Topologic Bomber Dragon` can only activate its effect once,different cards are different.But here is another bug.).The chains are c1 and c2,then you activate `Millennium-Eyes Restrict`'s effect and target `Topologic Bomber Dragon` as c3.
After the chains resolve,the monster in the main zone will be destroyed,because the `Effect.IsActiveType()` treats c2 as `TYPE_MONSTER` but treats c1 as `TYPE_SPELL`(The `Topologic Bomber Dragon` became `Millennium-Eyes Restrict`'s Equip Spell Card in c3).

**Comment by DailyShana** [comment] 2020-02-19 06:32
caused by https://github.com/Fluorohydride/ygopro-core/blob/297f4d995de7837b9d6f4d42037e1b467d528f18/processor.cpp#L4475
after resolving c2, `active_type` is reset, but the effect of c1 is same as c2, `Effect.IsActiveType()` will use the current type of the handler

**Closed** 2020-04-20 14:35 UTC
